"""Add language field to Query model

Revision ID: 0e051dd41b8d
Revises: 
Create Date: 2025-05-14 04:56:57.100619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e051dd41b8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_column('ai')

    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
