"""Add language field to File model

Revision ID: 1beace6b8e5e
Revises: ae830e7f45e0
Create Date: 2025-11-06 16:45:58.623440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beace6b8e5e'
down_revision = 'ae830e7f45e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=True))

    with op.batch_alter_table('knowledge_graph', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_graph_object'))
        batch_op.drop_index(batch_op.f('ix_knowledge_graph_relation'))
        batch_op.drop_index(batch_op.f('ix_knowledge_graph_subject'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_graph', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_graph_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_graph_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_graph_object'), ['object'], unique=False)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
