"""Add KnowledgeFact model

Revision ID: 7349d1b530c7
Revises: 1beace6b8e5e
Create Date: 2025-11-07 00:21:20.201631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7349d1b530c7'
down_revision = '1beace6b8e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('relation', sa.String(length=150), nullable=False),
    sa.Column('normalized_relation', sa.String(length=100), nullable=False),
    sa.Column('object', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_fact')
    # ### end Alembic commands ###
