"""Add answer column to Query model

Revision ID: ae830e7f45e0
Revises: 0e051dd41b8d
Create Date: 2025-05-14 13:14:26.767976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae830e7f45e0'
down_revision = '0e051dd41b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
